//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.18051에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace AdManagerClient.PreferenceTotalizeServicePloxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PreferenceTotalizeServiceSoap", Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    public partial class PreferenceTotalizeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAdListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPopupListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PreferenceTotalizeService() {
            this.Url = "http://localhost:8086/AdManagerWebserviceV5/ReportSummaryAd/PreferenceTotalizeSer" +
                "vice.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAdListCompletedEventHandler GetAdListCompleted;
        
        /// <remarks/>
        public event getPopupListCompletedEventHandler getPopupListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetAdList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PreferenceTotalizeModel GetAdList(HeaderModel header, PreferenceTotalizeModel model) {
            object[] results = this.Invoke("GetAdList", new object[] {
                        header,
                        model});
            return ((PreferenceTotalizeModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAdList(HeaderModel header, PreferenceTotalizeModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAdList", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public PreferenceTotalizeModel EndGetAdList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PreferenceTotalizeModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdListAsync(HeaderModel header, PreferenceTotalizeModel model) {
            this.GetAdListAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetAdListAsync(HeaderModel header, PreferenceTotalizeModel model, object userState) {
            if ((this.GetAdListOperationCompleted == null)) {
                this.GetAdListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdListOperationCompleted);
            }
            this.InvokeAsync("GetAdList", new object[] {
                        header,
                        model}, this.GetAdListOperationCompleted, userState);
        }
        
        private void OnGetAdListOperationCompleted(object arg) {
            if ((this.GetAdListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdListCompleted(this, new GetAdListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/getPopupList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PreferenceTotalizeModel getPopupList(HeaderModel header, PreferenceTotalizeModel model) {
            object[] results = this.Invoke("getPopupList", new object[] {
                        header,
                        model});
            return ((PreferenceTotalizeModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPopupList(HeaderModel header, PreferenceTotalizeModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPopupList", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public PreferenceTotalizeModel EndgetPopupList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PreferenceTotalizeModel)(results[0]));
        }
        
        /// <remarks/>
        public void getPopupListAsync(HeaderModel header, PreferenceTotalizeModel model) {
            this.getPopupListAsync(header, model, null);
        }
        
        /// <remarks/>
        public void getPopupListAsync(HeaderModel header, PreferenceTotalizeModel model, object userState) {
            if ((this.getPopupListOperationCompleted == null)) {
                this.getPopupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPopupListOperationCompleted);
            }
            this.InvokeAsync("getPopupList", new object[] {
                        header,
                        model}, this.getPopupListOperationCompleted, userState);
        }
        
        private void OngetPopupListOperationCompleted(object arg) {
            if ((this.getPopupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPopupListCompleted(this, new getPopupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class HeaderModel {
        
        private string clientKeyField;
        
        private string sysVersionField;
        
        private string userIDField;
        
        private string userLevelField;
        
        private string userClassField;
        
        private string userGroupField;
        
        /// <remarks/>
        public string ClientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SysVersion {
            get {
                return this.sysVersionField;
            }
            set {
                this.sysVersionField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        public string UserClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PreferenceTotalizeModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class BaseModel {
        
        private string resultDescField;
        
        private int resultCntField;
        
        private string resultCDField;
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCnt {
            get {
                return this.resultCntField;
            }
            set {
                this.resultCntField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCD {
            get {
                return this.resultCDField;
            }
            set {
                this.resultCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class PreferenceTotalizeModel : BaseModel {
        
        private string keyItemNoField;
        
        private string keyNoticeIdField;
        
        private string keyExmNoField;
        
        private string keySearchField;
        
        private string keyStartDayField;
        
        private string keyEndDayField;
        
        private string eventNameField;
        
        private int adExpCountField;
        
        private int popExpCountField;
        
        private int repCountField;
        
        private float repRateField;
        
        private string popExpTypeField;
        
        private System.Data.DataSet preferenceDataSetField;
        
        /// <remarks/>
        public string KeyItemNo {
            get {
                return this.keyItemNoField;
            }
            set {
                this.keyItemNoField = value;
            }
        }
        
        /// <remarks/>
        public string KeyNoticeId {
            get {
                return this.keyNoticeIdField;
            }
            set {
                this.keyNoticeIdField = value;
            }
        }
        
        /// <remarks/>
        public string KeyExmNo {
            get {
                return this.keyExmNoField;
            }
            set {
                this.keyExmNoField = value;
            }
        }
        
        /// <remarks/>
        public string KeySearch {
            get {
                return this.keySearchField;
            }
            set {
                this.keySearchField = value;
            }
        }
        
        /// <remarks/>
        public string KeyStartDay {
            get {
                return this.keyStartDayField;
            }
            set {
                this.keyStartDayField = value;
            }
        }
        
        /// <remarks/>
        public string KeyEndDay {
            get {
                return this.keyEndDayField;
            }
            set {
                this.keyEndDayField = value;
            }
        }
        
        /// <remarks/>
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        public int AdExpCount {
            get {
                return this.adExpCountField;
            }
            set {
                this.adExpCountField = value;
            }
        }
        
        /// <remarks/>
        public int PopExpCount {
            get {
                return this.popExpCountField;
            }
            set {
                this.popExpCountField = value;
            }
        }
        
        /// <remarks/>
        public int RepCount {
            get {
                return this.repCountField;
            }
            set {
                this.repCountField = value;
            }
        }
        
        /// <remarks/>
        public float RepRate {
            get {
                return this.repRateField;
            }
            set {
                this.repRateField = value;
            }
        }
        
        /// <remarks/>
        public string PopExpType {
            get {
                return this.popExpTypeField;
            }
            set {
                this.popExpTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet PreferenceDataSet {
            get {
                return this.preferenceDataSetField;
            }
            set {
                this.preferenceDataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAdListCompletedEventHandler(object sender, GetAdListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PreferenceTotalizeModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PreferenceTotalizeModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPopupListCompletedEventHandler(object sender, getPopupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPopupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPopupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PreferenceTotalizeModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PreferenceTotalizeModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591