//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.34209에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace AdManagerClient.AdvertiserServicePloxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdvertiserServiceSoap", Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    public partial class AdvertiserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAdvertiserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetAdvertiserUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetAdvertiserCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetAdvertiserDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJobClassListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdvertiserService() {
            this.Url = "http://localhost:8086/AdManagerWebserviceV7/Contract/AdvertiserService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAdvertiserListCompletedEventHandler GetAdvertiserListCompleted;
        
        /// <remarks/>
        public event SetAdvertiserUpdateCompletedEventHandler SetAdvertiserUpdateCompleted;
        
        /// <remarks/>
        public event SetAdvertiserCreateCompletedEventHandler SetAdvertiserCreateCompleted;
        
        /// <remarks/>
        public event SetAdvertiserDeleteCompletedEventHandler SetAdvertiserDeleteCompleted;
        
        /// <remarks/>
        public event GetJobClassListCompletedEventHandler GetJobClassListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetAdvertiserList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdvertiserModel GetAdvertiserList(HeaderModel header, AdvertiserModel advertiserModel) {
            object[] results = this.Invoke("GetAdvertiserList", new object[] {
                        header,
                        advertiserModel});
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAdvertiserList(HeaderModel header, AdvertiserModel advertiserModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAdvertiserList", new object[] {
                        header,
                        advertiserModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public AdvertiserModel EndGetAdvertiserList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdvertiserListAsync(HeaderModel header, AdvertiserModel advertiserModel) {
            this.GetAdvertiserListAsync(header, advertiserModel, null);
        }
        
        /// <remarks/>
        public void GetAdvertiserListAsync(HeaderModel header, AdvertiserModel advertiserModel, object userState) {
            if ((this.GetAdvertiserListOperationCompleted == null)) {
                this.GetAdvertiserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdvertiserListOperationCompleted);
            }
            this.InvokeAsync("GetAdvertiserList", new object[] {
                        header,
                        advertiserModel}, this.GetAdvertiserListOperationCompleted, userState);
        }
        
        private void OnGetAdvertiserListOperationCompleted(object arg) {
            if ((this.GetAdvertiserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdvertiserListCompleted(this, new GetAdvertiserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetAdvertiserUpdate", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdvertiserModel SetAdvertiserUpdate(HeaderModel header, AdvertiserModel advertiserModel) {
            object[] results = this.Invoke("SetAdvertiserUpdate", new object[] {
                        header,
                        advertiserModel});
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetAdvertiserUpdate(HeaderModel header, AdvertiserModel advertiserModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetAdvertiserUpdate", new object[] {
                        header,
                        advertiserModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public AdvertiserModel EndSetAdvertiserUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetAdvertiserUpdateAsync(HeaderModel header, AdvertiserModel advertiserModel) {
            this.SetAdvertiserUpdateAsync(header, advertiserModel, null);
        }
        
        /// <remarks/>
        public void SetAdvertiserUpdateAsync(HeaderModel header, AdvertiserModel advertiserModel, object userState) {
            if ((this.SetAdvertiserUpdateOperationCompleted == null)) {
                this.SetAdvertiserUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAdvertiserUpdateOperationCompleted);
            }
            this.InvokeAsync("SetAdvertiserUpdate", new object[] {
                        header,
                        advertiserModel}, this.SetAdvertiserUpdateOperationCompleted, userState);
        }
        
        private void OnSetAdvertiserUpdateOperationCompleted(object arg) {
            if ((this.SetAdvertiserUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAdvertiserUpdateCompleted(this, new SetAdvertiserUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetAdvertiserCreate", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdvertiserModel SetAdvertiserCreate(HeaderModel header, AdvertiserModel advertiserModel) {
            object[] results = this.Invoke("SetAdvertiserCreate", new object[] {
                        header,
                        advertiserModel});
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetAdvertiserCreate(HeaderModel header, AdvertiserModel advertiserModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetAdvertiserCreate", new object[] {
                        header,
                        advertiserModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public AdvertiserModel EndSetAdvertiserCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetAdvertiserCreateAsync(HeaderModel header, AdvertiserModel advertiserModel) {
            this.SetAdvertiserCreateAsync(header, advertiserModel, null);
        }
        
        /// <remarks/>
        public void SetAdvertiserCreateAsync(HeaderModel header, AdvertiserModel advertiserModel, object userState) {
            if ((this.SetAdvertiserCreateOperationCompleted == null)) {
                this.SetAdvertiserCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAdvertiserCreateOperationCompleted);
            }
            this.InvokeAsync("SetAdvertiserCreate", new object[] {
                        header,
                        advertiserModel}, this.SetAdvertiserCreateOperationCompleted, userState);
        }
        
        private void OnSetAdvertiserCreateOperationCompleted(object arg) {
            if ((this.SetAdvertiserCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAdvertiserCreateCompleted(this, new SetAdvertiserCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetAdvertiserDelete", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdvertiserModel SetAdvertiserDelete(HeaderModel header, AdvertiserModel advertiserModel) {
            object[] results = this.Invoke("SetAdvertiserDelete", new object[] {
                        header,
                        advertiserModel});
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetAdvertiserDelete(HeaderModel header, AdvertiserModel advertiserModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetAdvertiserDelete", new object[] {
                        header,
                        advertiserModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public AdvertiserModel EndSetAdvertiserDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetAdvertiserDeleteAsync(HeaderModel header, AdvertiserModel advertiserModel) {
            this.SetAdvertiserDeleteAsync(header, advertiserModel, null);
        }
        
        /// <remarks/>
        public void SetAdvertiserDeleteAsync(HeaderModel header, AdvertiserModel advertiserModel, object userState) {
            if ((this.SetAdvertiserDeleteOperationCompleted == null)) {
                this.SetAdvertiserDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAdvertiserDeleteOperationCompleted);
            }
            this.InvokeAsync("SetAdvertiserDelete", new object[] {
                        header,
                        advertiserModel}, this.SetAdvertiserDeleteOperationCompleted, userState);
        }
        
        private void OnSetAdvertiserDeleteOperationCompleted(object arg) {
            if ((this.SetAdvertiserDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAdvertiserDeleteCompleted(this, new SetAdvertiserDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetJobClassList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdvertiserModel GetJobClassList(HeaderModel header, AdvertiserModel advertiserModel) {
            object[] results = this.Invoke("GetJobClassList", new object[] {
                        header,
                        advertiserModel});
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetJobClassList(HeaderModel header, AdvertiserModel advertiserModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetJobClassList", new object[] {
                        header,
                        advertiserModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public AdvertiserModel EndGetJobClassList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AdvertiserModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetJobClassListAsync(HeaderModel header, AdvertiserModel advertiserModel) {
            this.GetJobClassListAsync(header, advertiserModel, null);
        }
        
        /// <remarks/>
        public void GetJobClassListAsync(HeaderModel header, AdvertiserModel advertiserModel, object userState) {
            if ((this.GetJobClassListOperationCompleted == null)) {
                this.GetJobClassListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJobClassListOperationCompleted);
            }
            this.InvokeAsync("GetJobClassList", new object[] {
                        header,
                        advertiserModel}, this.GetJobClassListOperationCompleted, userState);
        }
        
        private void OnGetJobClassListOperationCompleted(object arg) {
            if ((this.GetJobClassListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJobClassListCompleted(this, new GetJobClassListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class HeaderModel {
        
        private string clientKeyField;
        
        private string sysVersionField;
        
        private string userIDField;
        
        private string userLevelField;
        
        private string userClassField;
        
        private string userGroupField;
        
        /// <remarks/>
        public string ClientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SysVersion {
            get {
                return this.sysVersionField;
            }
            set {
                this.sysVersionField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        public string UserClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdvertiserModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class BaseModel {
        
        private string resultDescField;
        
        private int resultCntField;
        
        private string resultCDField;
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCnt {
            get {
                return this.resultCntField;
            }
            set {
                this.resultCntField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCD {
            get {
                return this.resultCDField;
            }
            set {
                this.resultCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class AdvertiserModel : BaseModel {
        
        private System.Data.DataSet advertiserDataSetField;
        
        private string searchKeyField;
        
        private string searchAdvertiserLevelField;
        
        private string searchchkAdState_10Field;
        
        private string searchRapField;
        
        private string advertiserCodeField;
        
        private string advertiserNameField;
        
        private string rapCodeField;
        
        private string rapNameField;
        
        private string commentField;
        
        private string useYnField;
        
        private string regDtField;
        
        private string modDtField;
        
        private string regIDField;
        
        private string jobCodeField;
        
        private string jobNameField;
        
        private string jobLevelField;
        
        /// <remarks/>
        public System.Data.DataSet AdvertiserDataSet {
            get {
                return this.advertiserDataSetField;
            }
            set {
                this.advertiserDataSetField = value;
            }
        }
        
        /// <remarks/>
        public string SearchKey {
            get {
                return this.searchKeyField;
            }
            set {
                this.searchKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SearchAdvertiserLevel {
            get {
                return this.searchAdvertiserLevelField;
            }
            set {
                this.searchAdvertiserLevelField = value;
            }
        }
        
        /// <remarks/>
        public string SearchchkAdState_10 {
            get {
                return this.searchchkAdState_10Field;
            }
            set {
                this.searchchkAdState_10Field = value;
            }
        }
        
        /// <remarks/>
        public string SearchRap {
            get {
                return this.searchRapField;
            }
            set {
                this.searchRapField = value;
            }
        }
        
        /// <remarks/>
        public string AdvertiserCode {
            get {
                return this.advertiserCodeField;
            }
            set {
                this.advertiserCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AdvertiserName {
            get {
                return this.advertiserNameField;
            }
            set {
                this.advertiserNameField = value;
            }
        }
        
        /// <remarks/>
        public string RapCode {
            get {
                return this.rapCodeField;
            }
            set {
                this.rapCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RapName {
            get {
                return this.rapNameField;
            }
            set {
                this.rapNameField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string UseYn {
            get {
                return this.useYnField;
            }
            set {
                this.useYnField = value;
            }
        }
        
        /// <remarks/>
        public string RegDt {
            get {
                return this.regDtField;
            }
            set {
                this.regDtField = value;
            }
        }
        
        /// <remarks/>
        public string ModDt {
            get {
                return this.modDtField;
            }
            set {
                this.modDtField = value;
            }
        }
        
        /// <remarks/>
        public string RegID {
            get {
                return this.regIDField;
            }
            set {
                this.regIDField = value;
            }
        }
        
        /// <remarks/>
        public string JobCode {
            get {
                return this.jobCodeField;
            }
            set {
                this.jobCodeField = value;
            }
        }
        
        /// <remarks/>
        public string JobName {
            get {
                return this.jobNameField;
            }
            set {
                this.jobNameField = value;
            }
        }
        
        /// <remarks/>
        public string JobLevel {
            get {
                return this.jobLevelField;
            }
            set {
                this.jobLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAdvertiserListCompletedEventHandler(object sender, GetAdvertiserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdvertiserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdvertiserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdvertiserModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdvertiserModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SetAdvertiserUpdateCompletedEventHandler(object sender, SetAdvertiserUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAdvertiserUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetAdvertiserUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdvertiserModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdvertiserModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SetAdvertiserCreateCompletedEventHandler(object sender, SetAdvertiserCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAdvertiserCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetAdvertiserCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdvertiserModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdvertiserModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SetAdvertiserDeleteCompletedEventHandler(object sender, SetAdvertiserDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAdvertiserDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetAdvertiserDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdvertiserModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdvertiserModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetJobClassListCompletedEventHandler(object sender, GetJobClassListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJobClassListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJobClassListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdvertiserModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdvertiserModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591