//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.18051에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace AdManagerClient.TimeSummaryServicePloxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimeSummaryServiceSoap", Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class TimeSummaryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAreaTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenreTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChannelTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAreaTimeByJavaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDateTimeByJavaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenreTimeByJavaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChannelTimeByJavaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TimeSummaryService() {
            this.Url = "http://localhost:8086/AdManagerWebserviceV5/ReportAd/TimeSummaryService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAreaTimeCompletedEventHandler GetAreaTimeCompleted;
        
        /// <remarks/>
        public event GetDateTimeCompletedEventHandler GetDateTimeCompleted;
        
        /// <remarks/>
        public event GetGenreTimeCompletedEventHandler GetGenreTimeCompleted;
        
        /// <remarks/>
        public event GetChannelTimeCompletedEventHandler GetChannelTimeCompleted;
        
        /// <remarks/>
        public event GetAreaTimeByJavaCompletedEventHandler GetAreaTimeByJavaCompleted;
        
        /// <remarks/>
        public event GetDateTimeByJavaCompletedEventHandler GetDateTimeByJavaCompleted;
        
        /// <remarks/>
        public event GetGenreTimeByJavaCompletedEventHandler GetGenreTimeByJavaCompleted;
        
        /// <remarks/>
        public event GetChannelTimeByJavaCompletedEventHandler GetChannelTimeByJavaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetAreaTime", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetAreaTime(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetAreaTime", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAreaTime(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAreaTime", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetAreaTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaTimeAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetAreaTimeAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetAreaTimeAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetAreaTimeOperationCompleted == null)) {
                this.GetAreaTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaTimeOperationCompleted);
            }
            this.InvokeAsync("GetAreaTime", new object[] {
                        header,
                        model}, this.GetAreaTimeOperationCompleted, userState);
        }
        
        private void OnGetAreaTimeOperationCompleted(object arg) {
            if ((this.GetAreaTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaTimeCompleted(this, new GetAreaTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetDateTime", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetDateTime(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetDateTime", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDateTime(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDateTime", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetDateTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetDateTimeAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetDateTimeAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetDateTimeAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetDateTimeOperationCompleted == null)) {
                this.GetDateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDateTimeOperationCompleted);
            }
            this.InvokeAsync("GetDateTime", new object[] {
                        header,
                        model}, this.GetDateTimeOperationCompleted, userState);
        }
        
        private void OnGetDateTimeOperationCompleted(object arg) {
            if ((this.GetDateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDateTimeCompleted(this, new GetDateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetGenreTime", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetGenreTime(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetGenreTime", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGenreTime(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGenreTime", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetGenreTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenreTimeAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetGenreTimeAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetGenreTimeAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetGenreTimeOperationCompleted == null)) {
                this.GetGenreTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenreTimeOperationCompleted);
            }
            this.InvokeAsync("GetGenreTime", new object[] {
                        header,
                        model}, this.GetGenreTimeOperationCompleted, userState);
        }
        
        private void OnGetGenreTimeOperationCompleted(object arg) {
            if ((this.GetGenreTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenreTimeCompleted(this, new GetGenreTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetChannelTime", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetChannelTime(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetChannelTime", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChannelTime(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChannelTime", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetChannelTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelTimeAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetChannelTimeAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetChannelTimeAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetChannelTimeOperationCompleted == null)) {
                this.GetChannelTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelTimeOperationCompleted);
            }
            this.InvokeAsync("GetChannelTime", new object[] {
                        header,
                        model}, this.GetChannelTimeOperationCompleted, userState);
        }
        
        private void OnGetChannelTimeOperationCompleted(object arg) {
            if ((this.GetChannelTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelTimeCompleted(this, new GetChannelTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetAreaTimeByJava", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetAreaTimeByJava(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetAreaTimeByJava", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAreaTimeByJava(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAreaTimeByJava", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetAreaTimeByJava(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaTimeByJavaAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetAreaTimeByJavaAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetAreaTimeByJavaAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetAreaTimeByJavaOperationCompleted == null)) {
                this.GetAreaTimeByJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaTimeByJavaOperationCompleted);
            }
            this.InvokeAsync("GetAreaTimeByJava", new object[] {
                        header,
                        model}, this.GetAreaTimeByJavaOperationCompleted, userState);
        }
        
        private void OnGetAreaTimeByJavaOperationCompleted(object arg) {
            if ((this.GetAreaTimeByJavaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaTimeByJavaCompleted(this, new GetAreaTimeByJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetDateTimeByJava", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetDateTimeByJava(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetDateTimeByJava", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDateTimeByJava(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDateTimeByJava", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetDateTimeByJava(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetDateTimeByJavaAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetDateTimeByJavaAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetDateTimeByJavaAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetDateTimeByJavaOperationCompleted == null)) {
                this.GetDateTimeByJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDateTimeByJavaOperationCompleted);
            }
            this.InvokeAsync("GetDateTimeByJava", new object[] {
                        header,
                        model}, this.GetDateTimeByJavaOperationCompleted, userState);
        }
        
        private void OnGetDateTimeByJavaOperationCompleted(object arg) {
            if ((this.GetDateTimeByJavaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDateTimeByJavaCompleted(this, new GetDateTimeByJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetGenreTimeByJava", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetGenreTimeByJava(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetGenreTimeByJava", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGenreTimeByJava(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGenreTimeByJava", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetGenreTimeByJava(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenreTimeByJavaAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetGenreTimeByJavaAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetGenreTimeByJavaAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetGenreTimeByJavaOperationCompleted == null)) {
                this.GetGenreTimeByJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenreTimeByJavaOperationCompleted);
            }
            this.InvokeAsync("GetGenreTimeByJava", new object[] {
                        header,
                        model}, this.GetGenreTimeByJavaOperationCompleted, userState);
        }
        
        private void OnGetGenreTimeByJavaOperationCompleted(object arg) {
            if ((this.GetGenreTimeByJavaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenreTimeByJavaCompleted(this, new GetGenreTimeByJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetChannelTimeByJava", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimeSummaryModel GetChannelTimeByJava(HeaderModel header, TimeSummaryModel model) {
            object[] results = this.Invoke("GetChannelTimeByJava", new object[] {
                        header,
                        model});
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChannelTimeByJava(HeaderModel header, TimeSummaryModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChannelTimeByJava", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public TimeSummaryModel EndGetChannelTimeByJava(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TimeSummaryModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelTimeByJavaAsync(HeaderModel header, TimeSummaryModel model) {
            this.GetChannelTimeByJavaAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetChannelTimeByJavaAsync(HeaderModel header, TimeSummaryModel model, object userState) {
            if ((this.GetChannelTimeByJavaOperationCompleted == null)) {
                this.GetChannelTimeByJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelTimeByJavaOperationCompleted);
            }
            this.InvokeAsync("GetChannelTimeByJava", new object[] {
                        header,
                        model}, this.GetChannelTimeByJavaOperationCompleted, userState);
        }
        
        private void OnGetChannelTimeByJavaOperationCompleted(object arg) {
            if ((this.GetChannelTimeByJavaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelTimeByJavaCompleted(this, new GetChannelTimeByJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class HeaderModel {
        
        private string clientKeyField;
        
        private string sysVersionField;
        
        private string userIDField;
        
        private string userLevelField;
        
        private string userClassField;
        
        private string userGroupField;
        
        /// <remarks/>
        public string ClientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SysVersion {
            get {
                return this.sysVersionField;
            }
            set {
                this.sysVersionField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        public string UserClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeSummaryModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class BaseModel {
        
        private string resultDescField;
        
        private int resultCntField;
        
        private string resultCDField;
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCnt {
            get {
                return this.resultCntField;
            }
            set {
                this.resultCntField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCD {
            get {
                return this.resultCDField;
            }
            set {
                this.resultCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class TimeSummaryModel : BaseModel {
        
        private System.Data.DataSet reportDataSetField;
        
        private object[] adListField;
        
        private string startDayField;
        
        private string endDayField;
        
        private string[] adListStrField;
        
        /// <remarks/>
        public System.Data.DataSet ReportDataSet {
            get {
                return this.reportDataSetField;
            }
            set {
                this.reportDataSetField = value;
            }
        }
        
        /// <remarks/>
        public object[] AdList {
            get {
                return this.adListField;
            }
            set {
                this.adListField = value;
            }
        }
        
        /// <remarks/>
        public string StartDay {
            get {
                return this.startDayField;
            }
            set {
                this.startDayField = value;
            }
        }
        
        /// <remarks/>
        public string EndDay {
            get {
                return this.endDayField;
            }
            set {
                this.endDayField = value;
            }
        }
        
        /// <remarks/>
        public string[] AdListStr {
            get {
                return this.adListStrField;
            }
            set {
                this.adListStrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAreaTimeCompletedEventHandler(object sender, GetAreaTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDateTimeCompletedEventHandler(object sender, GetDateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGenreTimeCompletedEventHandler(object sender, GetGenreTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenreTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenreTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChannelTimeCompletedEventHandler(object sender, GetChannelTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAreaTimeByJavaCompletedEventHandler(object sender, GetAreaTimeByJavaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaTimeByJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaTimeByJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDateTimeByJavaCompletedEventHandler(object sender, GetDateTimeByJavaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDateTimeByJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDateTimeByJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGenreTimeByJavaCompletedEventHandler(object sender, GetGenreTimeByJavaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenreTimeByJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenreTimeByJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChannelTimeByJavaCompletedEventHandler(object sender, GetChannelTimeByJavaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelTimeByJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelTimeByJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeSummaryModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeSummaryModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591