//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.18051에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace AdManagerClient.Sch3FormServiceProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Sch3FormServiceSoap", Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    public partial class Sch3FormService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetGenreListCSSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenreListDesignOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenreListTotOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChannelListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSeriesListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sch3FormService() {
            this.Url = "http://localhost:8086/AdManagerWebserviceV5/Schedule/Sch3FormService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetGenreListCSSCompletedEventHandler GetGenreListCSSCompleted;
        
        /// <remarks/>
        public event GetGenreListDesignCompletedEventHandler GetGenreListDesignCompleted;
        
        /// <remarks/>
        public event GetGenreListTotCompletedEventHandler GetGenreListTotCompleted;
        
        /// <remarks/>
        public event GetChannelListCompletedEventHandler GetChannelListCompleted;
        
        /// <remarks/>
        public event GetSeriesListCompletedEventHandler GetSeriesListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetGenreListCSS", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sch3FormModel GetGenreListCSS(HeaderModel header, Sch3FormModel model) {
            object[] results = this.Invoke("GetGenreListCSS", new object[] {
                        header,
                        model});
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGenreListCSS(HeaderModel header, Sch3FormModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGenreListCSS", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public Sch3FormModel EndGetGenreListCSS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenreListCSSAsync(HeaderModel header, Sch3FormModel model) {
            this.GetGenreListCSSAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetGenreListCSSAsync(HeaderModel header, Sch3FormModel model, object userState) {
            if ((this.GetGenreListCSSOperationCompleted == null)) {
                this.GetGenreListCSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenreListCSSOperationCompleted);
            }
            this.InvokeAsync("GetGenreListCSS", new object[] {
                        header,
                        model}, this.GetGenreListCSSOperationCompleted, userState);
        }
        
        private void OnGetGenreListCSSOperationCompleted(object arg) {
            if ((this.GetGenreListCSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenreListCSSCompleted(this, new GetGenreListCSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetGenreListDesign", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sch3FormModel GetGenreListDesign(HeaderModel header, Sch3FormModel model) {
            object[] results = this.Invoke("GetGenreListDesign", new object[] {
                        header,
                        model});
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGenreListDesign(HeaderModel header, Sch3FormModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGenreListDesign", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public Sch3FormModel EndGetGenreListDesign(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenreListDesignAsync(HeaderModel header, Sch3FormModel model) {
            this.GetGenreListDesignAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetGenreListDesignAsync(HeaderModel header, Sch3FormModel model, object userState) {
            if ((this.GetGenreListDesignOperationCompleted == null)) {
                this.GetGenreListDesignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenreListDesignOperationCompleted);
            }
            this.InvokeAsync("GetGenreListDesign", new object[] {
                        header,
                        model}, this.GetGenreListDesignOperationCompleted, userState);
        }
        
        private void OnGetGenreListDesignOperationCompleted(object arg) {
            if ((this.GetGenreListDesignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenreListDesignCompleted(this, new GetGenreListDesignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetGenreListTot", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sch3FormModel GetGenreListTot(HeaderModel header, Sch3FormModel model) {
            object[] results = this.Invoke("GetGenreListTot", new object[] {
                        header,
                        model});
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGenreListTot(HeaderModel header, Sch3FormModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGenreListTot", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public Sch3FormModel EndGetGenreListTot(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenreListTotAsync(HeaderModel header, Sch3FormModel model) {
            this.GetGenreListTotAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetGenreListTotAsync(HeaderModel header, Sch3FormModel model, object userState) {
            if ((this.GetGenreListTotOperationCompleted == null)) {
                this.GetGenreListTotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenreListTotOperationCompleted);
            }
            this.InvokeAsync("GetGenreListTot", new object[] {
                        header,
                        model}, this.GetGenreListTotOperationCompleted, userState);
        }
        
        private void OnGetGenreListTotOperationCompleted(object arg) {
            if ((this.GetGenreListTotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenreListTotCompleted(this, new GetGenreListTotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetChannelList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sch3FormModel GetChannelList(HeaderModel header, Sch3FormModel model) {
            object[] results = this.Invoke("GetChannelList", new object[] {
                        header,
                        model});
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChannelList(HeaderModel header, Sch3FormModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChannelList", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public Sch3FormModel EndGetChannelList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelListAsync(HeaderModel header, Sch3FormModel model) {
            this.GetChannelListAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetChannelListAsync(HeaderModel header, Sch3FormModel model, object userState) {
            if ((this.GetChannelListOperationCompleted == null)) {
                this.GetChannelListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelListOperationCompleted);
            }
            this.InvokeAsync("GetChannelList", new object[] {
                        header,
                        model}, this.GetChannelListOperationCompleted, userState);
        }
        
        private void OnGetChannelListOperationCompleted(object arg) {
            if ((this.GetChannelListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelListCompleted(this, new GetChannelListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetSeriesList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sch3FormModel GetSeriesList(HeaderModel header, Sch3FormModel model) {
            object[] results = this.Invoke("GetSeriesList", new object[] {
                        header,
                        model});
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSeriesList(HeaderModel header, Sch3FormModel model, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSeriesList", new object[] {
                        header,
                        model}, callback, asyncState);
        }
        
        /// <remarks/>
        public Sch3FormModel EndGetSeriesList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Sch3FormModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetSeriesListAsync(HeaderModel header, Sch3FormModel model) {
            this.GetSeriesListAsync(header, model, null);
        }
        
        /// <remarks/>
        public void GetSeriesListAsync(HeaderModel header, Sch3FormModel model, object userState) {
            if ((this.GetSeriesListOperationCompleted == null)) {
                this.GetSeriesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeriesListOperationCompleted);
            }
            this.InvokeAsync("GetSeriesList", new object[] {
                        header,
                        model}, this.GetSeriesListOperationCompleted, userState);
        }
        
        private void OnGetSeriesListOperationCompleted(object arg) {
            if ((this.GetSeriesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeriesListCompleted(this, new GetSeriesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class HeaderModel {
        
        private string clientKeyField;
        
        private string sysVersionField;
        
        private string userIDField;
        
        private string userLevelField;
        
        private string userClassField;
        
        private string userGroupField;
        
        /// <remarks/>
        public string ClientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SysVersion {
            get {
                return this.sysVersionField;
            }
            set {
                this.sysVersionField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        public string UserClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sch3FormModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class BaseModel {
        
        private string resultDescField;
        
        private int resultCntField;
        
        private string resultCDField;
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCnt {
            get {
                return this.resultCntField;
            }
            set {
                this.resultCntField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCD {
            get {
                return this.resultCDField;
            }
            set {
                this.resultCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class Sch3FormModel : BaseModel {
        
        private int itemNoField;
        
        private int mediaField;
        
        private int categoryField;
        
        private int genreField;
        
        private int channelField;
        
        private int dataTypeField;
        
        private System.Data.DataSet dsGenreField;
        
        private System.Data.DataSet dsChannelField;
        
        private System.Data.DataSet dsSeriesField;
        
        /// <remarks/>
        public int ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public int Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        /// <remarks/>
        public int Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public int Genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        public int Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public int DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DsGenre {
            get {
                return this.dsGenreField;
            }
            set {
                this.dsGenreField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DsChannel {
            get {
                return this.dsChannelField;
            }
            set {
                this.dsChannelField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet DsSeries {
            get {
                return this.dsSeriesField;
            }
            set {
                this.dsSeriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGenreListCSSCompletedEventHandler(object sender, GetGenreListCSSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenreListCSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenreListCSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sch3FormModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sch3FormModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGenreListDesignCompletedEventHandler(object sender, GetGenreListDesignCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenreListDesignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenreListDesignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sch3FormModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sch3FormModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGenreListTotCompletedEventHandler(object sender, GetGenreListTotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenreListTotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenreListTotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sch3FormModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sch3FormModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChannelListCompletedEventHandler(object sender, GetChannelListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sch3FormModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sch3FormModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSeriesListCompletedEventHandler(object sender, GetSeriesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeriesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeriesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sch3FormModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sch3FormModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591