//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.18051에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace AdManagerClient.ChannelGroupServicePloxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChannelGroupServiceSoap", Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    public partial class ChannelGroupService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetChannelGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChannelGroupDetailListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChannelList_pOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChannelList_ExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetChannelGroupUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetChannelGroupCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetChannelGroupDeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChannelGroupService() {
            this.Url = "http://localhost:8086/AdManagerWebserviceV5/Schedule/ChannelGroupService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetChannelGroupListCompletedEventHandler GetChannelGroupListCompleted;
        
        /// <remarks/>
        public event GetChannelGroupDetailListCompletedEventHandler GetChannelGroupDetailListCompleted;
        
        /// <remarks/>
        public event GetChannelList_pCompletedEventHandler GetChannelList_pCompleted;
        
        /// <remarks/>
        public event GetChannelList_ExcelCompletedEventHandler GetChannelList_ExcelCompleted;
        
        /// <remarks/>
        public event SetChannelGroupUpdateCompletedEventHandler SetChannelGroupUpdateCompleted;
        
        /// <remarks/>
        public event SetChannelGroupCreateCompletedEventHandler SetChannelGroupCreateCompleted;
        
        /// <remarks/>
        public event SetChannelGroupDeleteCompletedEventHandler SetChannelGroupDeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetChannelGroupList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChannelGroupModel GetChannelGroupList(HeaderModel header, ChannelGroupModel channelGroupModel) {
            object[] results = this.Invoke("GetChannelGroupList", new object[] {
                        header,
                        channelGroupModel});
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChannelGroupList(HeaderModel header, ChannelGroupModel channelGroupModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChannelGroupList", new object[] {
                        header,
                        channelGroupModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChannelGroupModel EndGetChannelGroupList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelGroupListAsync(HeaderModel header, ChannelGroupModel channelGroupModel) {
            this.GetChannelGroupListAsync(header, channelGroupModel, null);
        }
        
        /// <remarks/>
        public void GetChannelGroupListAsync(HeaderModel header, ChannelGroupModel channelGroupModel, object userState) {
            if ((this.GetChannelGroupListOperationCompleted == null)) {
                this.GetChannelGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelGroupListOperationCompleted);
            }
            this.InvokeAsync("GetChannelGroupList", new object[] {
                        header,
                        channelGroupModel}, this.GetChannelGroupListOperationCompleted, userState);
        }
        
        private void OnGetChannelGroupListOperationCompleted(object arg) {
            if ((this.GetChannelGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelGroupListCompleted(this, new GetChannelGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetChannelGroupDetailList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChannelGroupModel GetChannelGroupDetailList(HeaderModel header, ChannelGroupModel channelGroupModel) {
            object[] results = this.Invoke("GetChannelGroupDetailList", new object[] {
                        header,
                        channelGroupModel});
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChannelGroupDetailList(HeaderModel header, ChannelGroupModel channelGroupModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChannelGroupDetailList", new object[] {
                        header,
                        channelGroupModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChannelGroupModel EndGetChannelGroupDetailList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelGroupDetailListAsync(HeaderModel header, ChannelGroupModel channelGroupModel) {
            this.GetChannelGroupDetailListAsync(header, channelGroupModel, null);
        }
        
        /// <remarks/>
        public void GetChannelGroupDetailListAsync(HeaderModel header, ChannelGroupModel channelGroupModel, object userState) {
            if ((this.GetChannelGroupDetailListOperationCompleted == null)) {
                this.GetChannelGroupDetailListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelGroupDetailListOperationCompleted);
            }
            this.InvokeAsync("GetChannelGroupDetailList", new object[] {
                        header,
                        channelGroupModel}, this.GetChannelGroupDetailListOperationCompleted, userState);
        }
        
        private void OnGetChannelGroupDetailListOperationCompleted(object arg) {
            if ((this.GetChannelGroupDetailListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelGroupDetailListCompleted(this, new GetChannelGroupDetailListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetChannelList_p", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChannelGroupModel GetChannelList_p(HeaderModel header, ChannelGroupModel channelGroupModel) {
            object[] results = this.Invoke("GetChannelList_p", new object[] {
                        header,
                        channelGroupModel});
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChannelList_p(HeaderModel header, ChannelGroupModel channelGroupModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChannelList_p", new object[] {
                        header,
                        channelGroupModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChannelGroupModel EndGetChannelList_p(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelList_pAsync(HeaderModel header, ChannelGroupModel channelGroupModel) {
            this.GetChannelList_pAsync(header, channelGroupModel, null);
        }
        
        /// <remarks/>
        public void GetChannelList_pAsync(HeaderModel header, ChannelGroupModel channelGroupModel, object userState) {
            if ((this.GetChannelList_pOperationCompleted == null)) {
                this.GetChannelList_pOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelList_pOperationCompleted);
            }
            this.InvokeAsync("GetChannelList_p", new object[] {
                        header,
                        channelGroupModel}, this.GetChannelList_pOperationCompleted, userState);
        }
        
        private void OnGetChannelList_pOperationCompleted(object arg) {
            if ((this.GetChannelList_pCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelList_pCompleted(this, new GetChannelList_pCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetChannelList_Excel", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChannelGroupModel GetChannelList_Excel(HeaderModel header, ChannelGroupModel channelGroupModel) {
            object[] results = this.Invoke("GetChannelList_Excel", new object[] {
                        header,
                        channelGroupModel});
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChannelList_Excel(HeaderModel header, ChannelGroupModel channelGroupModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChannelList_Excel", new object[] {
                        header,
                        channelGroupModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChannelGroupModel EndGetChannelList_Excel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetChannelList_ExcelAsync(HeaderModel header, ChannelGroupModel channelGroupModel) {
            this.GetChannelList_ExcelAsync(header, channelGroupModel, null);
        }
        
        /// <remarks/>
        public void GetChannelList_ExcelAsync(HeaderModel header, ChannelGroupModel channelGroupModel, object userState) {
            if ((this.GetChannelList_ExcelOperationCompleted == null)) {
                this.GetChannelList_ExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChannelList_ExcelOperationCompleted);
            }
            this.InvokeAsync("GetChannelList_Excel", new object[] {
                        header,
                        channelGroupModel}, this.GetChannelList_ExcelOperationCompleted, userState);
        }
        
        private void OnGetChannelList_ExcelOperationCompleted(object arg) {
            if ((this.GetChannelList_ExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChannelList_ExcelCompleted(this, new GetChannelList_ExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetChannelGroupUpdate", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChannelGroupModel SetChannelGroupUpdate(HeaderModel header, ChannelGroupModel channelGroupModel) {
            object[] results = this.Invoke("SetChannelGroupUpdate", new object[] {
                        header,
                        channelGroupModel});
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetChannelGroupUpdate(HeaderModel header, ChannelGroupModel channelGroupModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetChannelGroupUpdate", new object[] {
                        header,
                        channelGroupModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChannelGroupModel EndSetChannelGroupUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetChannelGroupUpdateAsync(HeaderModel header, ChannelGroupModel channelGroupModel) {
            this.SetChannelGroupUpdateAsync(header, channelGroupModel, null);
        }
        
        /// <remarks/>
        public void SetChannelGroupUpdateAsync(HeaderModel header, ChannelGroupModel channelGroupModel, object userState) {
            if ((this.SetChannelGroupUpdateOperationCompleted == null)) {
                this.SetChannelGroupUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetChannelGroupUpdateOperationCompleted);
            }
            this.InvokeAsync("SetChannelGroupUpdate", new object[] {
                        header,
                        channelGroupModel}, this.SetChannelGroupUpdateOperationCompleted, userState);
        }
        
        private void OnSetChannelGroupUpdateOperationCompleted(object arg) {
            if ((this.SetChannelGroupUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetChannelGroupUpdateCompleted(this, new SetChannelGroupUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetChannelGroupCreate", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChannelGroupModel SetChannelGroupCreate(HeaderModel header, ChannelGroupModel channelGroupModel) {
            object[] results = this.Invoke("SetChannelGroupCreate", new object[] {
                        header,
                        channelGroupModel});
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetChannelGroupCreate(HeaderModel header, ChannelGroupModel channelGroupModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetChannelGroupCreate", new object[] {
                        header,
                        channelGroupModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChannelGroupModel EndSetChannelGroupCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetChannelGroupCreateAsync(HeaderModel header, ChannelGroupModel channelGroupModel) {
            this.SetChannelGroupCreateAsync(header, channelGroupModel, null);
        }
        
        /// <remarks/>
        public void SetChannelGroupCreateAsync(HeaderModel header, ChannelGroupModel channelGroupModel, object userState) {
            if ((this.SetChannelGroupCreateOperationCompleted == null)) {
                this.SetChannelGroupCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetChannelGroupCreateOperationCompleted);
            }
            this.InvokeAsync("SetChannelGroupCreate", new object[] {
                        header,
                        channelGroupModel}, this.SetChannelGroupCreateOperationCompleted, userState);
        }
        
        private void OnSetChannelGroupCreateOperationCompleted(object arg) {
            if ((this.SetChannelGroupCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetChannelGroupCreateCompleted(this, new SetChannelGroupCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetChannelGroupDelete", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChannelGroupModel SetChannelGroupDelete(HeaderModel header, ChannelGroupModel channelGroupModel) {
            object[] results = this.Invoke("SetChannelGroupDelete", new object[] {
                        header,
                        channelGroupModel});
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetChannelGroupDelete(HeaderModel header, ChannelGroupModel channelGroupModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetChannelGroupDelete", new object[] {
                        header,
                        channelGroupModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChannelGroupModel EndSetChannelGroupDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChannelGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetChannelGroupDeleteAsync(HeaderModel header, ChannelGroupModel channelGroupModel) {
            this.SetChannelGroupDeleteAsync(header, channelGroupModel, null);
        }
        
        /// <remarks/>
        public void SetChannelGroupDeleteAsync(HeaderModel header, ChannelGroupModel channelGroupModel, object userState) {
            if ((this.SetChannelGroupDeleteOperationCompleted == null)) {
                this.SetChannelGroupDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetChannelGroupDeleteOperationCompleted);
            }
            this.InvokeAsync("SetChannelGroupDelete", new object[] {
                        header,
                        channelGroupModel}, this.SetChannelGroupDeleteOperationCompleted, userState);
        }
        
        private void OnSetChannelGroupDeleteOperationCompleted(object arg) {
            if ((this.SetChannelGroupDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetChannelGroupDeleteCompleted(this, new SetChannelGroupDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class HeaderModel {
        
        private string clientKeyField;
        
        private string sysVersionField;
        
        private string userIDField;
        
        private string userLevelField;
        
        private string userClassField;
        
        private string userGroupField;
        
        /// <remarks/>
        public string ClientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SysVersion {
            get {
                return this.sysVersionField;
            }
            set {
                this.sysVersionField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        public string UserClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdGroupModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChannelGroupModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class BaseModel {
        
        private string resultDescField;
        
        private int resultCntField;
        
        private string resultCDField;
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCnt {
            get {
                return this.resultCntField;
            }
            set {
                this.resultCntField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCD {
            get {
                return this.resultCDField;
            }
            set {
                this.resultCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChannelGroupModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class AdGroupModel : BaseModel {
        
        private System.Data.DataSet adGroupDataSetField;
        
        private System.Data.DataSet mediaDataSetField;
        
        private string searchKeyField;
        
        private string mediaCodeField;
        
        private string mediaNameField;
        
        private string adGroupCodeField;
        
        private string adGroupNameField;
        
        private string menuTypeField;
        
        private string commentField;
        
        private string useYnField;
        
        private string useYnNameField;
        
        /// <remarks/>
        public System.Data.DataSet AdGroupDataSet {
            get {
                return this.adGroupDataSetField;
            }
            set {
                this.adGroupDataSetField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet MediaDataSet {
            get {
                return this.mediaDataSetField;
            }
            set {
                this.mediaDataSetField = value;
            }
        }
        
        /// <remarks/>
        public string SearchKey {
            get {
                return this.searchKeyField;
            }
            set {
                this.searchKeyField = value;
            }
        }
        
        /// <remarks/>
        public string MediaCode {
            get {
                return this.mediaCodeField;
            }
            set {
                this.mediaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MediaName {
            get {
                return this.mediaNameField;
            }
            set {
                this.mediaNameField = value;
            }
        }
        
        /// <remarks/>
        public string AdGroupCode {
            get {
                return this.adGroupCodeField;
            }
            set {
                this.adGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AdGroupName {
            get {
                return this.adGroupNameField;
            }
            set {
                this.adGroupNameField = value;
            }
        }
        
        /// <remarks/>
        public string MenuType {
            get {
                return this.menuTypeField;
            }
            set {
                this.menuTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string UseYn {
            get {
                return this.useYnField;
            }
            set {
                this.useYnField = value;
            }
        }
        
        /// <remarks/>
        public string UseYnName {
            get {
                return this.useYnNameField;
            }
            set {
                this.useYnNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class ChannelGroupModel : AdGroupModel {
        
        private System.Data.DataSet channelGroupDataSetField;
        
        private System.Data.DataSet channelGroup_pDataSetField;
        
        private string channelNoField;
        
        private string genreNameField;
        
        private string categoryCodeField;
        
        private string genreCodeField;
        
        /// <remarks/>
        public System.Data.DataSet ChannelGroupDataSet {
            get {
                return this.channelGroupDataSetField;
            }
            set {
                this.channelGroupDataSetField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ChannelGroup_pDataSet {
            get {
                return this.channelGroup_pDataSetField;
            }
            set {
                this.channelGroup_pDataSetField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelNo {
            get {
                return this.channelNoField;
            }
            set {
                this.channelNoField = value;
            }
        }
        
        /// <remarks/>
        public string GenreName {
            get {
                return this.genreNameField;
            }
            set {
                this.genreNameField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GenreCode {
            get {
                return this.genreCodeField;
            }
            set {
                this.genreCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChannelGroupListCompletedEventHandler(object sender, GetChannelGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChannelGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChannelGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChannelGroupDetailListCompletedEventHandler(object sender, GetChannelGroupDetailListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelGroupDetailListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelGroupDetailListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChannelGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChannelGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChannelList_pCompletedEventHandler(object sender, GetChannelList_pCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelList_pCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelList_pCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChannelGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChannelGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChannelList_ExcelCompletedEventHandler(object sender, GetChannelList_ExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChannelList_ExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChannelList_ExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChannelGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChannelGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetChannelGroupUpdateCompletedEventHandler(object sender, SetChannelGroupUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetChannelGroupUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetChannelGroupUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChannelGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChannelGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetChannelGroupCreateCompletedEventHandler(object sender, SetChannelGroupCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetChannelGroupCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetChannelGroupCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChannelGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChannelGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetChannelGroupDeleteCompletedEventHandler(object sender, SetChannelGroupDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetChannelGroupDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetChannelGroupDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChannelGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChannelGroupModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591