//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.18051에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace AdManagerClient.SchAppendAdServicePloxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SchAppendAdServiceSoap", Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    public partial class SchAppendAdService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSchAppendAdListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContractItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdDelete_ToOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdCreate_ToOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdOrderFirstOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdOrderUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdOrderDownOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchAppendAdOrderLastOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SchAppendAdService() {
            this.Url = "http://localhost:8086/AdManagerWebserviceV5/Schedule/SchAppendAdService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSchAppendAdListCompletedEventHandler GetSchAppendAdListCompleted;
        
        /// <remarks/>
        public event GetContractItemListCompletedEventHandler GetContractItemListCompleted;
        
        /// <remarks/>
        public event SetSchAppendSearchCompletedEventHandler SetSchAppendSearchCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdCreateCompletedEventHandler SetSchAppendAdCreateCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdDelete_ToCompletedEventHandler SetSchAppendAdDelete_ToCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdCreate_ToCompletedEventHandler SetSchAppendAdCreate_ToCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdDeleteCompletedEventHandler SetSchAppendAdDeleteCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdOrderFirstCompletedEventHandler SetSchAppendAdOrderFirstCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdOrderUpCompletedEventHandler SetSchAppendAdOrderUpCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdOrderDownCompletedEventHandler SetSchAppendAdOrderDownCompleted;
        
        /// <remarks/>
        public event SetSchAppendAdOrderLastCompletedEventHandler SetSchAppendAdOrderLastCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetSchAppendAdList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel GetSchAppendAdList(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("GetSchAppendAdList", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSchAppendAdList(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSchAppendAdList", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndGetSchAppendAdList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetSchAppendAdListAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.GetSchAppendAdListAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void GetSchAppendAdListAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.GetSchAppendAdListOperationCompleted == null)) {
                this.GetSchAppendAdListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSchAppendAdListOperationCompleted);
            }
            this.InvokeAsync("GetSchAppendAdList", new object[] {
                        header,
                        schAppendAdModel}, this.GetSchAppendAdListOperationCompleted, userState);
        }
        
        private void OnGetSchAppendAdListOperationCompleted(object arg) {
            if ((this.GetSchAppendAdListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSchAppendAdListCompleted(this, new GetSchAppendAdListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/GetContractItemList", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel GetContractItemList(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("GetContractItemList", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetContractItemList(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetContractItemList", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndGetContractItemList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetContractItemListAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.GetContractItemListAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void GetContractItemListAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.GetContractItemListOperationCompleted == null)) {
                this.GetContractItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContractItemListOperationCompleted);
            }
            this.InvokeAsync("GetContractItemList", new object[] {
                        header,
                        schAppendAdModel}, this.GetContractItemListOperationCompleted, userState);
        }
        
        private void OnGetContractItemListOperationCompleted(object arg) {
            if ((this.GetContractItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContractItemListCompleted(this, new GetContractItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendSearch", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendSearch(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendSearch", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendSearch(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendSearch", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendSearchAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendSearchAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendSearchAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendSearchOperationCompleted == null)) {
                this.SetSchAppendSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendSearchOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendSearch", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendSearchOperationCompleted, userState);
        }
        
        private void OnSetSchAppendSearchOperationCompleted(object arg) {
            if ((this.SetSchAppendSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendSearchCompleted(this, new SetSchAppendSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdCreate", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdCreate(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdCreate", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdCreate(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdCreate", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdCreateAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdCreateAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdCreateAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdCreateOperationCompleted == null)) {
                this.SetSchAppendAdCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdCreateOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdCreate", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdCreateOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdCreateOperationCompleted(object arg) {
            if ((this.SetSchAppendAdCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdCreateCompleted(this, new SetSchAppendAdCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdDelete_To", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdDelete_To(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdDelete_To", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdDelete_To(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdDelete_To", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdDelete_To(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdDelete_ToAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdDelete_ToAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdDelete_ToAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdDelete_ToOperationCompleted == null)) {
                this.SetSchAppendAdDelete_ToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdDelete_ToOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdDelete_To", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdDelete_ToOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdDelete_ToOperationCompleted(object arg) {
            if ((this.SetSchAppendAdDelete_ToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdDelete_ToCompleted(this, new SetSchAppendAdDelete_ToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdCreate_To", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdCreate_To(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdCreate_To", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdCreate_To(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdCreate_To", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdCreate_To(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdCreate_ToAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdCreate_ToAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdCreate_ToAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdCreate_ToOperationCompleted == null)) {
                this.SetSchAppendAdCreate_ToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdCreate_ToOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdCreate_To", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdCreate_ToOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdCreate_ToOperationCompleted(object arg) {
            if ((this.SetSchAppendAdCreate_ToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdCreate_ToCompleted(this, new SetSchAppendAdCreate_ToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdDelete", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdDelete(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdDelete", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdDelete(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdDelete", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdDeleteAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdDeleteAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdDeleteAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdDeleteOperationCompleted == null)) {
                this.SetSchAppendAdDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdDeleteOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdDelete", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdDeleteOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdDeleteOperationCompleted(object arg) {
            if ((this.SetSchAppendAdDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdDeleteCompleted(this, new SetSchAppendAdDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdOrderFirst", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdOrderFirst(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdOrderFirst", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdOrderFirst(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdOrderFirst", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdOrderFirst(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderFirstAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdOrderFirstAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderFirstAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdOrderFirstOperationCompleted == null)) {
                this.SetSchAppendAdOrderFirstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdOrderFirstOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdOrderFirst", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdOrderFirstOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdOrderFirstOperationCompleted(object arg) {
            if ((this.SetSchAppendAdOrderFirstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdOrderFirstCompleted(this, new SetSchAppendAdOrderFirstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdOrderUp", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdOrderUp(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdOrderUp", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdOrderUp(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdOrderUp", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdOrderUp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderUpAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdOrderUpAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderUpAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdOrderUpOperationCompleted == null)) {
                this.SetSchAppendAdOrderUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdOrderUpOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdOrderUp", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdOrderUpOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdOrderUpOperationCompleted(object arg) {
            if ((this.SetSchAppendAdOrderUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdOrderUpCompleted(this, new SetSchAppendAdOrderUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdOrderDown", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdOrderDown(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdOrderDown", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdOrderDown(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdOrderDown", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdOrderDown(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderDownAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdOrderDownAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderDownAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdOrderDownOperationCompleted == null)) {
                this.SetSchAppendAdOrderDownOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdOrderDownOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdOrderDown", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdOrderDownOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdOrderDownOperationCompleted(object arg) {
            if ((this.SetSchAppendAdOrderDownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdOrderDownCompleted(this, new SetSchAppendAdOrderDownCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://advmgt.hanafostv.com/AdManagerWebService/SetSchAppendAdOrderLast", RequestNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", ResponseNamespace="http://advmgt.hanafostv.com/AdManagerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SchAppendAdModel SetSchAppendAdOrderLast(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            object[] results = this.Invoke("SetSchAppendAdOrderLast", new object[] {
                        header,
                        schAppendAdModel});
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSchAppendAdOrderLast(HeaderModel header, SchAppendAdModel schAppendAdModel, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSchAppendAdOrderLast", new object[] {
                        header,
                        schAppendAdModel}, callback, asyncState);
        }
        
        /// <remarks/>
        public SchAppendAdModel EndSetSchAppendAdOrderLast(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SchAppendAdModel)(results[0]));
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderLastAsync(HeaderModel header, SchAppendAdModel schAppendAdModel) {
            this.SetSchAppendAdOrderLastAsync(header, schAppendAdModel, null);
        }
        
        /// <remarks/>
        public void SetSchAppendAdOrderLastAsync(HeaderModel header, SchAppendAdModel schAppendAdModel, object userState) {
            if ((this.SetSchAppendAdOrderLastOperationCompleted == null)) {
                this.SetSchAppendAdOrderLastOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchAppendAdOrderLastOperationCompleted);
            }
            this.InvokeAsync("SetSchAppendAdOrderLast", new object[] {
                        header,
                        schAppendAdModel}, this.SetSchAppendAdOrderLastOperationCompleted, userState);
        }
        
        private void OnSetSchAppendAdOrderLastOperationCompleted(object arg) {
            if ((this.SetSchAppendAdOrderLastCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchAppendAdOrderLastCompleted(this, new SetSchAppendAdOrderLastCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class HeaderModel {
        
        private string clientKeyField;
        
        private string sysVersionField;
        
        private string userIDField;
        
        private string userLevelField;
        
        private string userClassField;
        
        private string userGroupField;
        
        /// <remarks/>
        public string ClientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SysVersion {
            get {
                return this.sysVersionField;
            }
            set {
                this.sysVersionField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserLevel {
            get {
                return this.userLevelField;
            }
            set {
                this.userLevelField = value;
            }
        }
        
        /// <remarks/>
        public string UserClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public string UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchAppendAdModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class BaseModel {
        
        private string resultDescField;
        
        private int resultCntField;
        
        private string resultCDField;
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCnt {
            get {
                return this.resultCntField;
            }
            set {
                this.resultCntField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCD {
            get {
                return this.resultCDField;
            }
            set {
                this.resultCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://advmgt.hanafostv.com/AdManagerWebService/")]
    public partial class SchAppendAdModel : BaseModel {
        
        private int fileListCountField;
        
        private System.Data.DataSet scheduleDataSetField;
        
        private string searchKeyField;
        
        private string searchMediaCodeField;
        
        private string searchRapCodeField;
        
        private string searchAgencyCodeField;
        
        private string searchAdvertiserCodeField;
        
        private string searchContractStateField;
        
        private string searchAdClassField;
        
        private string searchchkAdState_10Field;
        
        private string searchchkAdState_20Field;
        
        private string searchchkAdState_30Field;
        
        private string searchchkAdState_40Field;
        
        private string mediaCodeField;
        
        private string scheduleOrderField;
        
        private string itemNoField;
        
        private string itemNameField;
        
        private string lastOrderField;
        
        /// <remarks/>
        public int FileListCount {
            get {
                return this.fileListCountField;
            }
            set {
                this.fileListCountField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ScheduleDataSet {
            get {
                return this.scheduleDataSetField;
            }
            set {
                this.scheduleDataSetField = value;
            }
        }
        
        /// <remarks/>
        public string SearchKey {
            get {
                return this.searchKeyField;
            }
            set {
                this.searchKeyField = value;
            }
        }
        
        /// <remarks/>
        public string SearchMediaCode {
            get {
                return this.searchMediaCodeField;
            }
            set {
                this.searchMediaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SearchRapCode {
            get {
                return this.searchRapCodeField;
            }
            set {
                this.searchRapCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SearchAgencyCode {
            get {
                return this.searchAgencyCodeField;
            }
            set {
                this.searchAgencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SearchAdvertiserCode {
            get {
                return this.searchAdvertiserCodeField;
            }
            set {
                this.searchAdvertiserCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SearchContractState {
            get {
                return this.searchContractStateField;
            }
            set {
                this.searchContractStateField = value;
            }
        }
        
        /// <remarks/>
        public string SearchAdClass {
            get {
                return this.searchAdClassField;
            }
            set {
                this.searchAdClassField = value;
            }
        }
        
        /// <remarks/>
        public string SearchchkAdState_10 {
            get {
                return this.searchchkAdState_10Field;
            }
            set {
                this.searchchkAdState_10Field = value;
            }
        }
        
        /// <remarks/>
        public string SearchchkAdState_20 {
            get {
                return this.searchchkAdState_20Field;
            }
            set {
                this.searchchkAdState_20Field = value;
            }
        }
        
        /// <remarks/>
        public string SearchchkAdState_30 {
            get {
                return this.searchchkAdState_30Field;
            }
            set {
                this.searchchkAdState_30Field = value;
            }
        }
        
        /// <remarks/>
        public string SearchchkAdState_40 {
            get {
                return this.searchchkAdState_40Field;
            }
            set {
                this.searchchkAdState_40Field = value;
            }
        }
        
        /// <remarks/>
        public string MediaCode {
            get {
                return this.mediaCodeField;
            }
            set {
                this.mediaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ScheduleOrder {
            get {
                return this.scheduleOrderField;
            }
            set {
                this.scheduleOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastOrder {
            get {
                return this.lastOrderField;
            }
            set {
                this.lastOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSchAppendAdListCompletedEventHandler(object sender, GetSchAppendAdListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSchAppendAdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSchAppendAdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetContractItemListCompletedEventHandler(object sender, GetContractItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContractItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContractItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendSearchCompletedEventHandler(object sender, SetSchAppendSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdCreateCompletedEventHandler(object sender, SetSchAppendAdCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdDelete_ToCompletedEventHandler(object sender, SetSchAppendAdDelete_ToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdDelete_ToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdDelete_ToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdCreate_ToCompletedEventHandler(object sender, SetSchAppendAdCreate_ToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdCreate_ToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdCreate_ToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdDeleteCompletedEventHandler(object sender, SetSchAppendAdDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdOrderFirstCompletedEventHandler(object sender, SetSchAppendAdOrderFirstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdOrderFirstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdOrderFirstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdOrderUpCompletedEventHandler(object sender, SetSchAppendAdOrderUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdOrderUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdOrderUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdOrderDownCompletedEventHandler(object sender, SetSchAppendAdOrderDownCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdOrderDownCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdOrderDownCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetSchAppendAdOrderLastCompletedEventHandler(object sender, SetSchAppendAdOrderLastCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSchAppendAdOrderLastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSchAppendAdOrderLastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchAppendAdModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchAppendAdModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591